---
  title: "BDA - Project"
author: "Anonymous"
output: 
  pdf_document: 
  toc: yes
toc_depth: 1
keep_tex: true
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r, echo=FALSE}
library(aaltobda)
library (mvtnorm)

library("rstan")
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')

```


```{r, echo=TRUE, tidy=FALSE}
library("ggplot2")
library("bayesplot")
theme_set(bayesplot::theme_default(base_family = "sans"))
library(loo)

```

# Regression models
```{r}
colnames(dataset)[14] = "Par"
rownames(dataset)[3] = "Mar"
df <- data.frame(dataset)
plot(1:12, df[,1])
matplot(1:12, df, )
#plot(month ~ states,df)
```


## Use the dataset for sum of fires in each state:

```{r, echo=FALSE}
library(readr)
amazon <- read_csv("amazon.csv")
#View(amazon)

#levels(factor(amazon$state))

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Janeiro")
    amazon$month[i]="January"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Fevereiro")
    amazon$month[i]="February"
}

for (i in 1:dim(amazon)[1]) {
  if(startsWith(amazon$month[i],"Mar"))
    amazon$month[i]="March"
}


for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Abril")
    amazon$month[i]="April"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Maio")
    amazon$month[i]="May"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Junho")
    amazon$month[i]="June"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Julho")
    amazon$month[i]="July"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Agosto")
    amazon$month[i]="August"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Setembro")
    amazon$month[i]="September"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Outubro")
    amazon$month[i]="October"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Novembro")
    amazon$month[i]="November"
}

for (i in 1:dim(amazon)[1]) {
  if(amazon$month[i]=="Dezembro")
    amazon$month[i]="Dicember"
}



# Remove dots:
for (i in 1:length(amazon$number)) {
  if (amazon$number[i] %% 1 != 0) {
    amazon$number[i] = amazon$number[i]*1000
  }
}

amazon=as.data.frame(amazon)
years=levels(factor(sort(amazon$year)))
states=levels(factor(sort(amazon$state)))
dataset=as.data.frame(matrix(rep(0,length(years)*length(states)), nrow=length(years), byrow=TRUE))
colnames(dataset)=states
rownames(dataset)=years
for (j in 1:length(states)) {
  for (i in 1:length(years)) {
    dataset[i,j] = sum(amazon[which(amazon$year==years[i] & amazon$state==states[j]),4])
  }
}
```

# Pooled regression model w.r.t the states of Brazil and sum of number of fires per year

Neg binomial regression model erikseen hierarkinen ja pooled. Ennustamaan tulipalojen summaa per vuosi per state ttai kk keskiarvoa
```{r tidy=FALSE}
y=dataset[,1]
for (i in 2:23) {
  y=cbind(y,dataset[,i])
}
y=as.vector(y)

# x = c(rep(1,20), rep(2,20), rep(3,20), rep(4,20),rep(5,20),rep(6,20),rep(7,20),rep(8,20),rep(9,20),rep(10,20),rep(11,20),
#       rep(12,20),rep(13,20),rep(14,20),rep(15,20),rep(16,20),rep(17,20),rep(18,20),rep(19,20),rep(20,20),rep(21,20),rep(22,20),
#       rep(23,20))
x = rep(1998:2017, 23)
xpred = 2018
N <- length(y)
data=list(N =N, x=x, y=y, xpred = xpred)


fit1 <- stan("regression_pooled.stan", data = data)
```


```{r}
alpha <- as.matrix(fit1)[,1]
beta <- as.matrix(fit1)[,2]
plot(alpha, beta, main="Scatterplot of draws of alpha and beta",
   xlab="Alpha ", ylab="Beta", pch=10)

stan_trace(p, pars=c("ypred"))
stan_dens(fit1, pars=c("ypred"))
fit1

draws <- as.data.frame(fit1)
hist(draws$ypred)
```












# Separate regression model
```{r}

```
















## Hierarchical Regression model
```{r}
y=dataset[,1]
for (i in 2:23) {
  y=cbind(y,dataset[,i])
}
y=as.vector(y)
y=y[1:80]
x = rep(1998:2017, 4)
# xx = c(rep(1,20), rep(2,20), rep(3,20), rep(4,20),rep(5,20),rep(6,20),rep(7,20),rep(8,20),rep(9,20),rep(10,20),rep(11,20),
#       rep(12,20),rep(13,20),rep(14,20),rep(15,20),rep(16,20),rep(17,20),rep(18,20),rep(19,20),rep(20,20),rep(21,20),rep(22,20),
#       rep(23,20))
xx =c(rep(1,20), rep(2,20), rep(3,20), rep(4,20))
N <- length(y)          # N of observations per state
K <- 4           # N of states
xpred <- 2018
data=list(N =N, K=K, x=x, xx=xx, y=y, xpred = xpred)


fit2 <- stan("regression_hierarchical.stan",
             data = data,
             chains = 4,     # number of Markov chains
             iter =4000,    # total number of iterations per chain
             warmup=3000,
             cores = 2       # number of cores (could use one per chain)
)
```



```{r}
data = list(
  N = 4*20,
  K = 4,
  x = x[1:80],
  xx =c(rep(1,20), rep(2,20), rep(3,20), rep(4,20)),
  y = y[1:80]
)
fit2 <- stan("poisson.stan", 
             data = data,
             chains = 4,     # number of Markov chains
             iter =4000,    # total number of iterations per chain
             warmup=3000,
             cores = 2 
)

```


```{r}
alpha <- as.matrix(fit2)[,1]
beta <- as.matrix(fit2)[,2]
#plot(alpha, beta, main="Scatterplot of draws of alpha and beta",
#   xlab="Alpha ", ylab="Beta", pch=10)

#stan_trace(fit2, pars=c("ypred"))
stan_dens(fit2, pars=c("ypred"))

pred <- as.data.frame(extract(fit2, "ypred"))
colMeans(pred)
colMeans(dataset)
fit2

#draws <- as.data.frame(fit2)
#hist(draws$ypred)


# LOO estimates
loo_regression=loo(fit2)
plot(loo_regression)

log_lik_h <- extract_log_lik(fit2, merge_chains = FALSE)
#log_lik_h
r_eff_h <- relative_eff(exp(log_lik_h))
r_eff_h
#loo_h <- loo(log_lik_h, r_eff = r_eff_h, save_psis=TRUE, cores=2 )
loo_h <- loo(log_lik_h, save_psis=TRUE, cores=2 )
print(loo_h)



```

```{r}
# Hierarchical Model
samples_h = extract(object=fit2, permuted = TRUE, inc_warmup = FALSE, include = TRUE)

log_lik_h <- extract_log_lik(fit2, merge_chains = FALSE)
r_eff_h <- relative_eff(exp(log_lik_h))
loo_model_h <- loo(log_lik_h, r_eff = r_eff_h, save_psis=TRUE, cores=2 )
print(loo_model_h)
plot(loo_model_h)

# PSIS-LOO values
loo_model_h$estimates[1]
```


```{r}
# Save the best model so far to this var:
fit2_best_so_far <- fit2
```




